### ISSUE TITLE
有關android 5之後的外接SD card路徑選擇

### ISSUE THREAD

**Issue by sm7428290** [H-Viewer-Sites/Apply#1]
作者你好:

android 5之後的版本第三方app要存取外接儲存裝置時需要透過內建檔案瀏覽器利用document tree的方式來指定路徑，因此希望作者能更新支援android 5之後版本的下載資料夾外接儲存裝置路徑選擇，或是直接讓使用者可以key in資料夾路徑，第一張圖是H viewer的使用截圖，其他張則是另一可指定外接SD card的應用程式截圖

謝謝

![screenshot_2016-09-07-21-01-37_ml puredark hviewer](https://cloud.githubusercontent.com/assets/22043370/18314000/c9284c08-7543-11e6-92c4-88a338a1842f.png)
![screenshot_2016-09-07-21-02-23_com hippo ehviewer](https://cloud.githubusercontent.com/assets/22043370/18313999/c92807c0-7543-11e6-9033-d7e832c1d451.png)
![screenshot_2016-09-07-21-02-40_com android documentsui](https://cloud.githubusercontent.com/assets/22043370/18314002/c93aa8b2-7543-11e6-9957-304d1415539b.png)
![screenshot_2016-09-07-21-02-46_com hippo ehviewer](https://cloud.githubusercontent.com/assets/22043370/18314001/c92d372c-7543-11e6-9c86-03909aa98c9c.png)

**Comment by wspl** [comment]
你好，应用使用问题相关 issues 应该到 [https://github.com/PureDark/H-Viewer](https://github.com/PureDark/H-Viewer)，这个 Repo 是专门用来提交新站点添加申请的。感谢配合。
