### ISSUE TITLE
宅男女神

### ISSUE THREAD

**Issue by fk19901019fk** [H-Viewer-Sites/Apply#11]
宅男女神这个网站有的图不会显示出来..

**Comment by fk19901019fk** [comment]
http://m.zngirls.com/
这个网站的全
WWW开头的不全

**Comment by PureDark** [comment]
“有的”指哪些，不给个例子我也没法测试啊

至于你说的www不全？我没发现，更何况m的移动版详情页是没有tag的，而没有tag就没法进行搜索

这个站的每一个tag都能获取到其独有的网址，点开TAG面板，可以单独读取任何一个tag对应的列表，这个优势比移动版大多了
