### ISSUE TITLE
提交某(gu)歌搜索的json

### ISSUE THREAD

**Issue by Soooya** [H-Viewer-Sites/Apply#12]
## 某歌搜索的json
- 可以搜索，翻页，比网页方便多了。
- 图片页加载图片。
- 详情页是文本化的网页，带有超链接。
- 评论页是此页面内的外链。
越来越感觉这个是神器啊！
直接贴代码吧。
`{
    "categories": [
        {
            "cid": 1,
            "title": "某页面",
            "url": "https://www.google.com/search?q=hentai&newwindow=1&safe=off&start={page:0:10}"
        }
    ],
    "title": "某歌",
    "indexUrl": "https://www.google.com/search?q=hentai&newwindow=1&safe=off&start={page:0:10}",
    "galleryUrl": "{idCode:}",
    "searchUrl": "https://www.google.com/search?q={keyword:}&newwindow=1&safe=off&start={page:0:10}",
    "loginUrl": "https://www.google.com",
    "flag": "preloadGallery",
    "indexRule": {
        "item": {
            "selector": "#center_col div.srg div.g"
        },
        "idCode": {
            "fun": "attr",
            "param": "href",
            "selector": "h3.r a"
        },
        "title": {
            "fun": "text",
            "selector": "h3.r a"
        }
    },
    "galleryRule": {
        "commentRule":  {
            "item": {
                "selector": "a[href]",
                "regex":"http"
            },
            "author": {
                "fun": "html",
                "selector": "a"
            },
            "content": {
                "fun": "attr",
                "param": "href",
                "selector": "a"
            }
        },
        "pictureRule": {
            "item": {
                "selector": "a[href]"
            },
            "thumbnail": {
                "regex": "((http|https)://[^\"]*?\\.(jpg|png|gif|bmp))",
                "selector": "this"
            },
            "url":  {
                "regex": "((http|https)://[^\"]*?\\.(jpg|png|gif|bmp))",
                "selector": "this"
            }
        },
        "title": {
            "fun": "text",
            "selector": "title"
        },
        "description":{
            "fun": "html",
            "selector": "body"
        },
        "cover": {
                "regex": "((http|https)://[^\"]*?\\.(jpg|png|gif|bmp))",
                "selector": "this"
        }
    }
}`

**Comment by Soooya** [comment]
缺个相对链接补全

**Comment by PureDark** [comment]
不适合放到任何分类，这种邪门用法还是不好放上市场的233

**Comment by Soooya** [comment]
写着玩的，随意处理吧。
不过如果同时有相对链接和绝对链接，
要是想补全相对链接，是不是只能用regex选相对链接然后replacement补全。
剩下绝对链接就没办法选中了？

**Comment by PureDark** [comment]
不是，wiki中写得很清楚了、相对连接和绝对链接不用进行处理
取到相对连接后应用内会自动根据获取到html的网址对相对链接进行补全

**Comment by Soooya** [comment]
嗯，图片可以的。不过description和comments 里的相对链接点不动。不过我猜这个应该不是你的重点。
