### ISSUE TITLE
视频站  在线播放类型的

### ISSUE THREAD

**Issue by yidao123** [H-Viewer-Sites/Apply#14]
http://hpjav.com/tw
另外再给dalao推荐个视频导航类的网站 质量挺不错的 https://theporndude.com/

**Comment by PureDark** [comment]
写了，因为需要点击操作才会加载视频，需要等下个版本更新

EDIT: 已更新，视频已添加到官方市场

**Comment by zhihaofans** [comment]
@PureDark 你忘记删掉searchUrl了
