### ISSUE TITLE
如何获取最新最全的站点

### ISSUE THREAD

**Issue by Reckfu1** [H-Viewer-Sites/Apply#15]
获取最新最全的站点请在应用内的站点市场  请问应用内的站点市场是什么意思。。抱歉我新手- -

**Comment by zhihaofans** [comment]
@Reckfu1 
1.从左边拉出菜单(图1)
2.点击上面的站点市场(图1)
3.点击`添加`就可以了(图2)
---
# 图1:
![](https://github.com/PureDark/H-Viewer/raw/master/images/3.png)

# 图2:
![](https://github.com/PureDark/H-Viewer/raw/master/images/12.png)

**Comment by Reckfu1** [comment]
@zhihaofans 你好 我的意思是应用的名称是什么 我在app store没找到 抱歉我这愚蠢的表达能力- -

**Comment by zhihaofans** [comment]
@Reckfu1 

app store是指ios的app store吗? ios版的话现在还没出[【查看详情】](https://github.com/PureDark/H-Viewer/issues/46)

安卓版的话作者好像只在 [CoolApk/酷安](http://www.coolapk.com/apk/ml.puredark.hviewer) 上架了

**Comment by Reckfu1** [comment]
@zhihaofans  嗯是ios的 希望早点出 嘿嘿~
