### ISSUE TITLE
(*'▽'*)♪

### ISSUE THREAD

**Issue by LX-huaiyin** [H-Viewer-Sites/Apply#17]
堆糖，topit

**Comment by zhihaofans** [comment]
堆糖已添加 ([a88b7a8](https://github.com/H-Viewer-Sites/zhihaofans/commit/4c6cddc0081ccd8542c8c2a29fc5fc349338e5b2#diff-7d550619825743e4589ad76aee4778ea))

有问题请指出

**Comment by zhihaofans** [comment]
@liudifuxiao topit无法浏览，[测试结果](http://tool.chinaz.com/pagestatus/?url=topit.me)
