### ISSUE TITLE
求添加站点~谢谢 老司机

### ISSUE THREAD

**Issue by guoqiang2589** [H-Viewer-Sites/Apply#2]
http://momoniji.com/ 桃色虹画像 -二次元萌え画像エロ画像まとめ
http://okkisokuho.com/ エロ画像まとめ おっき速報
http://egv.cc/  二次エロ画像ビューア
http://charaud.com/ きゃらうど！ | アニメやゲームの美少女キャラのエロ画像を集めています。
http://nijinchu.com/  にじんちゅ -二次元エロ画像-
http://moeshunga.com/  萌春画/二次元フルカラーエロ同人誌・漫画
........有点多 随意添加 谢谢啦

**Comment by PureDark** [comment]
有好几个已经写了，有几个定位重复就不写了
