### ISSUE TITLE
首页地址不分页的怎么写"indexUrl"-。-

### ISSUE THREAD

**Issue by xxxxuanran** [H-Viewer-Sites/Apply#23]
http://h.bilibili.com/eden/picture_area#/cos/hot
简单的看了一下“怎么自定义新的站点规则”，基于E-shuushuu的规则简单填补修改了一下，结果是无返回数据-，-
有大佬帮忙吗

**Comment by zhihaofans** [comment]
不分页的indexUrl就不用填页码参数，加个js滚动就可以

**Comment by PureDark** [comment]
flag里填上jsNeededIndex和jsScroll
