### ISSUE TITLE
有技术老哥帮忙把这个无修网站编辑一蛤吗？

### ISSUE THREAD

**Issue by peterpan0513** [H-Viewer-Sites/Apply#26]
首先十分感谢创作者为我提供了这么破费的app。hentai.cafe这个美妙的网站我真的非常想添加进去，可惜自己不会弄。希望能得到各位技术老哥的支持，要是创作者本人的话就更好了

**Comment by PureDark** [comment]
加了

**Comment by peterpan0513** [comment]
作者大哥你看看能不能完善一蛤，因为网站只能tag搜索而不能搜索其他，连作者名跟题目名都不可以，能不能麻烦一蛤做到跟原网站的搜索功能，谢谢。

**Comment by peterpan0513** [comment]
@PureDark  老哥麻烦修正一蛤，新添加的无修网站没法搜索作者名称，多个tag搜索显示错误，作品的标签页面没有附带作者。拜托了老哥。
