### ISSUE TITLE
新站提供另外一个妹子图-meizitu

### ISSUE THREAD

**Issue by sosmygirl** [H-Viewer-Sites/Apply#4]
{
"categories":[
 {
                "url": "http://www.meizitu.com/a/list_1_{page:1}.html",
                "title": "首页",
                "cid": 1
            },
            {
                "url": "http://www.meizitu.com/a/xinggan_2_{page:1}.html",
                "title":"性感浴室",
                "cid": 2
            },
            {
                "url": "http://www.meizitu.com/a/sifang_5_{page:1}.html",
                "title": "私房美腿",
                "cid": 3
            },
            { "url": "http://www.meizitu.com/a/qingchun_3_{page:1}.html",
                "title": "清纯可爱",
                "cid": 4
            },
            {
        "url": "http://www.meizitu.com/a/meizi_4_{page:1}.html",
                "title": "妹子",
                "cid": 5
            },
        {
        "url": "http://www.meizitu.com/a/xiaoqingxin_6_{page:1}.html",
                "title": "小清新",
                "cid": 6
            },
        {
        "url": "http://www.meizitu.com/a/nvshen_7_{page:1}.html",
                "title": "女神",
                "cid": 7
        },
        {
        "url": "http://www.meizitu.com/a/mote_9_{page:1}.html",
                "title": "模特车模",
                "cid": 8
        },
            {
        "url": "http://www.meizitu.com/a/bijini_10_{page:1}.html",
                "title": "比基尼",
                "cid": 9
        },
        {
        "url": "http://www.meizitu.com/a/baobei_11_{page:1}.html",
                "title": "足球宝贝",
                "cid": 10
        },
        {
        "url": "http://www.meizitu.com/a/wangluo_13_{page:1}.html",
                "title": "网络女神",
                "cid": 11
        },
        {
        "url": "http://www.meizitu.com/a/luoli_12_{page:1}.html",
                "title": "萝莉",
                "cid": 12
        },
        {
        "url": "http://www.meizitu.com/a/rihan_14_{page:1}.html",
                "title": "日韩",
                "cid": 13
        }
    ],
    "extraRule":{},
    "flag":"noTag",
    "galleryRule":{
        "datetime":{
        "fun":"html",
        "selector":"div.month_year"
        },
        "item":{
        "selector":"p img"
        },
        "pictureThumbnail":{
        "fun":"attr",
        "param":"src",
        "selector":"img"
        },
        "pictureUrl":{
        "fun":"attr",
        "param":"src",
        "selector":"img"},
        "tags":{
        "fun":"html",
        "selector":"div.metaRight\u003ep"
        },
        "title":{
        "fun":"html",
        "selector":"div.metaRight > h2 > a"
        }
        },
     "galleryUrl":"http://www.meizitu.com/a/{idCode:}.html",
     "gid":12,
     "index":3,
     "indexRule":{
        "cover":{
         "fun":"attr",
        "param":"src",
        "selector":".pic a img"
         },
        "idCode":{
         "fun":"attr",
         "param":"href",
         "regex":"http://www\.meizitu\.com/a/(\d+).html",
         "selector":"h3.tit  a"
         },
         "item":{
        "selector":"ul.wp-list > li > div.con"
        },
         "title":{
        "fun":"html",
         "selector":"h3.tit a"
         }
         },
     "indexUrl":"http://www.meizitu.com/a/list_1_{page:1}.html",
     "sid":94,
     "title":"meizitu",
     "versionCode":1
     }

**Comment by sosmygirl** [comment]
网站title不规范，有的会有<b>xxxxx</b>的问题

**Comment by PureDark** [comment]
抱歉，之前一直忘了检查这边的issue，因为忘记watch了发了新issue我也没收到通知、

测试可用，虽然某处正则似乎忘记加转义符
加上后就好了

我之后就放到市场上，话说站点市场下面的站点描述的那句话是可以自定义的、就像酷安的小编点评一样、我先用站点的介绍了，如果有想说的话我给你加上、

**Comment by PureDark** [comment]
accepted
