### ISSUE TITLE
新站点：ACfun文章区-漫画/小说版

### ISSUE THREAD

**Issue by zhihaofans** [H-Viewer-Sites/Apply#9]
## [配置文件](https://github.com/zhihaofans/H-Viewer.sites/blob/master/sites/acfun_comic.json)

1.小说也混进来了，这个没办法解决

2.直接抓取网页的，所以cover无法获取(只能从json api获取)，等我研究懂json path再弄。

**Comment by PureDark** [comment]
研究通了没？弄得完善一点了我再放上去

**Comment by zhihaofans** [comment]
## →[JSON 版](https://github.com/zhihaofans/H-Viewer.sites/blob/master/sites/acfun_comic_json.json)

在线测试通过，实机测试内容空白(已排除手机网络问题)，和非JSON的那个相比添加了`searchUrl`、`cover`、`categories`

由于官方api需要在GET请求中带的`deviceType:1`的`header`，所以我用我的服务器中转了

建议在配置文件加个`header`的选项(代替`cookie`)

**Comment by zhihaofans** [comment]
## 新站点配置文件
- [羁绊网/幻之羁绊动漫网](https://github.com/zhihaofans/H-Viewer.sites/blob/master/sites/005.tv.json) (www.005.tv)
- [胖次网](https://github.com/zhihaofans/H-Viewer.sites/blob/master/sites/pangci.json) (www.pangci.cc)

---

@PureDark

**Comment by PureDark** [comment]
`div#area-player>p>img` 不能取到图片，用`div#area-player img`，`item`加上`regex:"漫画"`，把所有内部不含有`漫画`两个字的`item`排除掉，这样可能会把一些有图的也意外排除，却可以提升总体的使用体验，或者你也可以总结一下可能包含漫画的标题的关键字，一起放到正则里，比如  `(?:漫画|条漫|彩漫)` ，加`?:` 是不取括号内的数据，不然出来的结果就只有漫画两个字了
自定义`header`可以有，跟`cookie`虽然重复了，但是需要自定义`header`的情况是少数，大部分时候最多只需要`cookie`，所以`cookie`单独占一个属性会比较方便，不需要合并成`header`，下个版本单独增加一个`header`属性吧

**Comment by zhihaofans** [comment]
## 懂了⊙ω⊙之前css用得少不是很了解

还有，胖次网名字前面多了个空格，酷安有人提醒我才发现
